version: '2'
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
      - /var/www/epelia:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - db
  php:
    build: ./php
    volumes:
      - /var/www/epelia:/code
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    depends_on:
      - db
  db:
    image: postgres:9.5.22-alpine
    volumes:
      - /var/www/epelia:/code
      - /var/www/epelia/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=epelia
    command: ["postgres", "-c", "log_statement=all"]
